services:
  - type: web
    name: ek-portfolio-backend
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /docs
    envVars:
      - key: CORS_ORIGINS
        value: https://ekamruth.github.io/ek-portfolio/
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: gpt-oss-120b:free
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
